# Export a weapon's animation files to GZDoom: one MD3 with every frame, the baked
# atlas, a MODELDEF mapping game sprite frames to model frames, and a test .pk3.
#   blender.exe -b --factory-startup --python kit/gz_export.py -- gz_revolver.py [flat|vr]
import bpy, sys, os, zipfile
from mathutils import Vector, Matrix, Quaternion

KIT = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[sys.argv.index("--") + 1:]
exec(open(os.path.join(KIT, "gz_md3.py")).read())
VARIANT = args[1] if len(args) > 1 else "flat"      # "flat" (screen) or "vr" (controller)
exec(open(os.path.join(KIT, args[0])).read())


VIEW = globals().get("SPACE", "hand") == "view"
O = (0.0, 0.0, 0.0) if VIEW else ORIGIN


def to_md3(p):
    # GZDoom draws MD3 +Y on the viewer's RIGHT (hh79/gzdoomvr gvr4.13.2.2, models.cpp) [verified-live 2026-09-17]:
    # writing -x mirrored the gun, so the cylinder swung out to the right in game.
    return ((p.y - O[1]) * UNITS_PER_M, (p.x - O[0]) * UNITS_PER_M, (p.z - O[2]) * UNITS_PER_M)


def gather(blend, count, rest, want_uvs, motion_scale=1.0):
    """Every frame of one animation file, in the root's rest space."""
    bpy.ops.wm.open_mainfile(filepath=blend)
    sc = bpy.context.scene
    objs = sorted((o for o in sc.objects if o.type == 'MESH'), key=lambda o: o.name)
    frames, uvs = [], []
    for f in range(1, count + 1):
        sc.frame_set(f)
        dg = bpy.context.evaluated_depsgraph_get()
        if rest is None:
            # "view": keep the Blender first-person camera space (camera at the origin, looking +Y);
            # "hand": relative to the gun's rest pose, for attaching to a VR controller
            rest = Matrix.Identity(4) if VIEW else sc.objects[ROOT].matrix_world.copy()
        inv = rest.inverted()
        k = motion_scale
        if k != 1.0:
            # shrink how far the whole gun moves away from its rest pose (parts still move fully)
            D = rest.inverted() @ sc.objects[ROOT].matrix_world
            q = Quaternion().slerp(D.to_quaternion(), k)
            D_small = Matrix.Translation(D.to_translation() * k) @ q.to_matrix().to_4x4()
            inv = D_small @ D.inverted() @ rest.inverted()
        verts = []
        for o in objs:
            eo = o.evaluated_get(dg)
            me = eo.to_mesh()
            M = inv @ eo.matrix_world
            R = M.to_3x3()
            shown = not o.hide_render
            centre = M @ Vector((0, 0, 0))
            uvl = me.uv_layers.active.data
            for poly in me.polygons:
                n = (R @ poly.normal).normalized()
                loops = list(poly.loop_indices)
                for k in range(1, len(loops) - 1):
                    # HUD models are not back-face culled, so one copy per triangle is enough.
                    # The x -> md3 Y mapping is a mirror, so the winding is reversed to match.
                    for li in (loops[0], loops[k + 1], loops[k]):
                        p = M @ me.vertices[me.loops[li].vertex_index].co if shown else centre
                        verts.append((to_md3(p), (n.y, n.x, n.z)))
                        if want_uvs and f == 1:
                            uvs.append(tuple(uvl[li].uv))
            eo.to_mesh_clear()
        frames.append(verts)
    return frames, uvs, rest


all_frames, uvs, rest, first = [], None, None, {}
for name, blend, count in ANIMS:
    first[name] = len(all_frames)
    fr, uv, rest = gather(blend, count, rest, uvs is None, globals().get("GUN_MOTION_SCALE", {}).get(name, 1.0))
    if uvs is None:
        uvs = uv
    assert len(fr[0]) == len(uvs), f"{name}: vertex count differs from the first animation"
    all_frames += fr

os.makedirs(OUT_DIR, exist_ok=True)
md3_path = os.path.join(OUT_DIR, NAME + ".md3")
tris = [(i, i + 1, i + 2) for i in range(0, len(uvs), 3)]
nsurf, nv, nt = write_md3(md3_path, NAME, all_frames, (tris, uvs), f"{MODEL_PATH}/{NAME}.png")
print(f"md3: {len(all_frames)} frames, {nsurf} surfaces, {nv} verts, {nt} tris")

lines = [f"// Generated by kit/gz_export.py from kit/{args[0]}. Do not edit by hand.",
         f"Model {NAME}", "{", f'   Path "{MODEL_PATH}"', f'   Model 0 "{NAME}.md3"', f'   Skin 0 "{NAME}.png"']
lines += [f'   SurfaceSkin 0 {i} "{NAME}.png"' for i in range(nsurf)]
lines += ["   Scale 1.0 1.0 1.0", "   NOINTERPOLATION", ""]
lines += [f"   FrameIndex {spr} {letter} 0 {first[anim] + frame - 1}" for spr, letter, anim, frame in SPRITES]
lines += ["}"]
modeldef = "\n".join(lines) + "\n"
with open(os.path.join(OUT_DIR, "modeldef." + NAME + ".txt"), "w") as f:
    f.write(modeldef)

pk3 = os.path.join(OUT_DIR, PK3)
with zipfile.ZipFile(pk3, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("modeldef." + NAME, modeldef)
    z.write(md3_path, f"{MODEL_PATH}/{NAME}.md3")
    z.write(os.path.join(OUT_DIR, NAME + ".png"), f"{MODEL_PATH}/{NAME}.png")
print("pk3", pk3)
