# Export a weapon's animation files to GZDoom: one MD3 with every frame, the baked
# atlas, a MODELDEF mapping game sprite frames to model frames, and a test .pk3.
#   blender.exe -b --factory-startup --python kit/gz_export.py -- gz_revolver.py
import bpy, sys, os, zipfile
from mathutils import Vector

KIT = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[sys.argv.index("--") + 1:]
exec(open(os.path.join(KIT, "gz_md3.py")).read())
exec(open(os.path.join(KIT, args[0])).read())


def to_md3(p):
    return ((p.y - ORIGIN[1]) * UNITS_PER_M, -(p.x - ORIGIN[0]) * UNITS_PER_M, (p.z - ORIGIN[2]) * UNITS_PER_M)


def gather(blend, count, rest, want_uvs):
    """Every frame of one animation file, in the root's rest space."""
    bpy.ops.wm.open_mainfile(filepath=blend)
    sc = bpy.context.scene
    objs = sorted((o for o in sc.objects if o.type == 'MESH'), key=lambda o: o.name)
    frames, uvs = [], []
    for f in range(1, count + 1):
        sc.frame_set(f)
        dg = bpy.context.evaluated_depsgraph_get()
        if rest is None:
            rest = sc.objects[ROOT].matrix_world.copy()
        inv = rest.inverted()
        verts = []
        for o in objs:
            eo = o.evaluated_get(dg)
            me = eo.to_mesh()
            M = inv @ eo.matrix_world
            R = M.to_3x3()
            shown = not o.hide_render
            centre = M @ Vector((0, 0, 0))
            uvl = me.uv_layers.active.data
            for poly in me.polygons:
                n = (R @ poly.normal).normalized()
                loops = list(poly.loop_indices)
                for k in range(1, len(loops) - 1):
                    tri = (loops[0], loops[k], loops[k + 1])
                    # front copy, then a reversed copy facing the other way (two-sided,
                    # so the winding convention cannot make the gun invisible)
                    for corners, nn in ((tri, n), (tri[::-1], -n)):
                        for li in corners:
                            p = M @ me.vertices[me.loops[li].vertex_index].co if shown else centre
                            verts.append((to_md3(p), (nn.y, -nn.x, nn.z)))
                            if want_uvs and f == 1:
                                uvs.append(tuple(uvl[li].uv))
            eo.to_mesh_clear()
        frames.append(verts)
    return frames, uvs, rest


all_frames, uvs, rest, first = [], None, None, {}
for name, blend, count in ANIMS:
    first[name] = len(all_frames)
    fr, uv, rest = gather(blend, count, rest, uvs is None)
    if uvs is None:
        uvs = uv
    assert len(fr[0]) == len(uvs), f"{name}: vertex count differs from the first animation"
    all_frames += fr

os.makedirs(OUT_DIR, exist_ok=True)
md3_path = os.path.join(OUT_DIR, NAME + ".md3")
tris = [(i, i + 1, i + 2) for i in range(0, len(uvs), 3)]
nsurf, nv, nt = write_md3(md3_path, NAME, all_frames, (tris, uvs), f"{MODEL_PATH}/{NAME}.png")
print(f"md3: {len(all_frames)} frames, {nsurf} surfaces, {nv} verts, {nt} tris")

lines = [f"// Generated by kit/gz_export.py from kit/{args[0]}. Do not edit by hand.",
         f"Model {NAME}", "{", f'   Path "{MODEL_PATH}"', f'   Model 0 "{NAME}.md3"', f'   Skin 0 "{NAME}.png"']
lines += [f'   SurfaceSkin 0 {i} "{NAME}.png"' for i in range(nsurf)]
lines += ["   Scale 1.0 1.0 1.0", "   NOINTERPOLATION", ""]
lines += [f"   FrameIndex {spr} {letter} 0 {first[anim] + frame - 1}" for spr, letter, anim, frame in SPRITES]
lines += ["}"]
modeldef = "\n".join(lines) + "\n"
with open(os.path.join(OUT_DIR, "modeldef." + NAME + ".txt"), "w") as f:
    f.write(modeldef)

pk3 = os.path.join(OUT_DIR, PK3)
with zipfile.ZipFile(pk3, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("modeldef." + NAME, modeldef)
    z.write(md3_path, f"{MODEL_PATH}/{NAME}.md3")
    z.write(os.path.join(OUT_DIR, NAME + ".png"), f"{MODEL_PATH}/{NAME}.png")
print("pk3", pk3)
